### ISSUE TITLE
Myhtml dependecy is deprecated

### ISSUE THREAD

**Issue by franciscoGPS** [celestinecr/celestine#42]
This shard is great but since one of its dependencies is deprecated, is throwing errors.
Myhtml creator even suggests to switch to Lexbor. 

https://github.com/kostya/myhtml/issues/26

<img width="875" alt="image" src="https://user-images.githubusercontent.com/6760672/196071649-7f15e8dd-13e1-48ca-b02b-119b28e71b93.png">

**Comment by sol-vin** [comment]
Shoot, I've been working hard on `raylib-cr` but I'll see what I can do to fix that but IDK if this is something that can be easily fixed without investing a bunch of time rewriting.

**Comment by sol-vin** [comment]
Update to this issue. Turns out I need to do two things, 1. remove "myhtml" entirely and move it into a development dependency , 2. update the specs to use Lexbor instead.

**Comment by sol-vin** [comment]
I took out specs for the time being, going to add them back later but for now this should work again.
