### ISSUE TITLE
`Celestine::Meta::Context#width=` doesn't work with `Int32`

### ISSUE THREAD

**Issue by sugarfi** [celestinecr/celestine#9]
When passing an `Int32` to `Celestine::Meta::Context#width=`, an error is thrown, since this function is only overloaded for the type `Float64`.
Input:
```
Celestine.draw do |ctx|
  ctx.width = 800
end
```
Expected behavior: SVG width is set to 800
Actual behavior:
```
Error: no overload matches 'Celestine::Meta::Context#width=' with type Int32

Overloads are:
 - Celestine::Meta::Context#width=(width : Float64)
```

**Comment by redcodefinal** [comment]
Ah yeah, I need to change that to the type `IFNumber?`. I'll shoot a pull request on this here in a minute.

**Comment by redcodefinal** [comment]
#10
